<br/><fontsize='1'><tableclass='xdebug-errorxe-uncaught-exception'dir='ltr'border='1'cellspacing='0'cellpadding='1'><tr><thalign='left'bgcolor='#f57900'colspan="5"><spanstyle='background-color: #cc0000;color: #fce94f;font-size: x-large;'>(!)</span>Fatalerror: UncaughtPDOException: SQLSTATE[
	HY093
]: Invalidparameternumber: numberofboundvariablesdoesnotmatchnumberoftokensinC: \wamp64\www\autocare\api\model\Veiculo.phponline<i>38</i></th></tr><tr><thalign='left'bgcolor='#f57900'colspan="5"><spanstyle='background-color: #cc0000;color: #fce94f;font-size: x-large;'>(!)</span>PDOException: SQLSTATE[
	HY093
]: Invalidparameternumber: numberofboundvariablesdoesnotmatchnumberoftokensinC: \wamp64\www\autocare\api\model\Veiculo.phponline<i>38</i></th></tr><tr><thalign='left'bgcolor='#e9b96e'colspan='5'>CallStack</th></tr><tr><thalign='center'bgcolor='#eeeeec'>#</th><thalign='left'bgcolor='#eeeeec'>Time</th><thalign='left'bgcolor='#eeeeec'>Memory</th><thalign='left'bgcolor='#eeeeec'>Function</th><thalign='left'bgcolor='#eeeeec'>Location</th></tr><tr><tdbgcolor='#eeeeec'align='center'>1</td><tdbgcolor='#eeeeec'align='center'>0.0003</td><tdbgcolor='#eeeeec'align='right'>442104</td><tdbgcolor='#eeeeec'>{
	main
}()</td><tdtitle='C: \wamp64\www\autocare\api\index.php'bgcolor='#eeeeec'>...\index.php<b>: </b>0</td></tr><tr><tdbgcolor='#eeeeec'align='center'>2</td><tdbgcolor='#eeeeec'align='center'>0.0004</td><tdbgcolor='#eeeeec'align='right'>442784</td><tdbgcolor='#eeeeec'>require_once(<fontcolor='#00bb00'>'C: \wamp64\www\autocare\api\routes\Routes.php</font>)</td><tdtitle='C: \wamp64\www\autocare\api\index.php'bgcolor='#eeeeec'>...\index.php<b>: </b>6</td></tr><tr><tdbgcolor='#eeeeec'align='center'>3</td><tdbgcolor='#eeeeec'align='center'>0.0007</td><tdbgcolor='#eeeeec'align='right'>525256</td><tdbgcolor='#eeeeec'>handleUsuarioRoute(<span>$method=</span><span>&#39;PUT&#39;</span>,
<span>$id=</span><span>&#39;1&#39;</span>)</td><tdtitle='C: \wamp64\www\autocare\api\routes\Routes.php'bgcolor='#eeeeec'>...\Routes.php<b>: </b>34</td></tr><tr><tdbgcolor='#eeeeec'align='center'>4</td><tdbgcolor='#eeeeec'align='center'>0.0248</td><tdbgcolor='#eeeeec'align='right'>573408</td><tdbgcolor='#eeeeec'>VeiculoController->update(<span>$data=</span><span>[
	&#39;ano&#39;=&gt;2090,
	&#39;apelido&#39;=&gt;&#39;LancerMonstro2&#39;,
	&#39;id_usuario&#39;=&gt;8,
	&#39;id_modelo_veiculo&#39;=&gt;1,
	&#39;id&#39;=&gt;&#39;1&#39;
]</span>)</td><tdtitle='C: \wamp64\www\autocare\api\routes\Veiculo.php'bgcolor='#eeeeec'>...\Veiculo.php<b>: </b>31</td></tr><tr><tdbgcolor='#eeeeec'align='center'>5</td><tdbgcolor='#eeeeec'align='center'>0.0248</td><tdbgcolor='#eeeeec'align='right'>573408</td><tdbgcolor='#eeeeec'>Veiculo->update()</td><tdtitle='C: \wamp64\www\autocare\api\controller\VeiculoController.php'bgcolor='#eeeeec'>...\VeiculoController.php<b>: </b>32</td></tr><tr><tdbgcolor='#eeeeec'align='center'>6</td><tdbgcolor='#eeeeec'align='center'>0.0248</td><tdbgcolor='#eeeeec'align='right'>575416</td><tdbgcolor='#eeeeec'><ahref='http: //www.php.net/PDOStatement.execute'target='_new'>execute</a>()</td><tdtitle='C: \wamp64\www\autocare\api\model\Veiculo.php'bgcolor='#eeeeec'>...\Veiculo.php<b>: </b>38</td></tr></table></font>